# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M6.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3

con = sqlite3.connect('BookTitles')
cur = con.cursor()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.l1 = QtWidgets.QLabel(Form)
        self.l1.setGeometry(QtCore.QRect(20, 90, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.t1 = QtWidgets.QLineEdit(Form)
        self.t1.setGeometry(QtCore.QRect(120, 90, 113, 22))
        self.t1.setObjectName("t1")
        self.l2 = QtWidgets.QLabel(Form)
        self.l2.setGeometry(QtCore.QRect(30, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.t3 = QtWidgets.QLineEdit(Form)
        self.t3.setGeometry(QtCore.QRect(120, 200, 113, 22))
        self.t3.setObjectName("t3")
        self.t3.setValidator(QtGui.QIntValidator())
        self.p1 = QtWidgets.QPushButton(Form)
        self.p1.setGeometry(QtCore.QRect(260, 70, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.clicked.connect(self.book_title)
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(Form)
        self.p2.setGeometry(QtCore.QRect(260, 190, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.p2.setFont(font)
        self.p2.setObjectName("p2")
        self.p2.clicked.connect(self.find_total)
        self.t2 = QtWidgets.QLineEdit(Form)
        self.t2.setGeometry(QtCore.QRect(250, 120, 113, 22))
        self.t2.setObjectName("t2")
        self.t4 = QtWidgets.QLineEdit(Form)
        self.t4.setGeometry(QtCore.QRect(250, 240, 113, 22))
        self.t4.setObjectName("t4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def book_title(self, prc=0):
        nam = self.t1.text()
        copies = self.t3.text()
        sel = "SELECT * from books WHERE Title=='" + nam + "';"
        sel1 = "SELECT Price from books WHERE Title=='" + nam + "';"
        cur.execute(sel)
        record = cur.fetchone()
        if record is None:
            self.p1.clicked.connect(self.show_popup)
        else:
            cur.execute(sel1)
            num = cur.fetchone()
            num = str(num[0])
            self.t2.setText(num)

    def find_total(self):
        no = self.t2.text()
        no = int(no)
        quantity = self.t3.text()
        quantity = int(quantity)
        prc = 0
        prc = prc + (no * quantity)
        prc = str(prc)
        self.t4.setText(prc)

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Book Titles")
        msg.setText("Book not found")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l1.setText(_translate("Form", "Book Title:"))
        self.l2.setText(_translate("Form", "Quantity :"))
        self.p1.setText(_translate("Form", "Find Price"))
        self.p2.setText(_translate("Form", "Find Total"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
